add_newline = false

[line_break]
disabled = true

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character """

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
format = "[$symbol [$branch](117)]($style)"
symbol = ""
style = "bright-black"

[git_status]
format = "[[ *($conflicted$untracked$modified$staged$renamed$deleted)](119) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "="
untracked = "?"
modified = "ﰣ"
staged = "+"
renamed = "凜 "
deleted = "ﮁ"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
min_time = 10_000
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[[$symbol](220) $virtualenv]($style) "
symbol = ""
style = "bright-black"
